name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
projects:
  - "eli-davidson-portfolio/1"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        This will be tracked in our organization-wide project board at: https://github.com/orgs/eli-davidson-portfolio/projects/1

  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Functionality (Something isn't working)
        - UI/UX (Visual or usability issue)
        - Performance (Slowness or resource issues)
        - Security (Potential vulnerability)
        - Data (Incorrect or missing data)
        - Integration (API or service connection)
    validations:
      required: true

  - type: input
    id: project_context
    attributes:
      label: Project Component
      description: Which specific component or area is affected?
      placeholder: "e.g., Login Form, Data Table, API Endpoint"
    validations:
      required: true

  - type: dropdown
    id: impact_scope
    attributes:
      label: Impact Scope
      description: How many users/features are affected?
      options:
        - All Users (System-wide impact)
        - Many Users (Major feature affected)
        - Some Users (Specific use case)
        - Edge Case (Rare conditions)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: "A clear and concise description of what the bug is"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "A clear and concise description of what you expected to happen"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Bug Frequency
      description: How often does this bug occur?
      options:
        - Always (100% reproducible)
        - Often (Happens frequently)
        - Sometimes (Intermittent)
        - Rarely (Hard to reproduce)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical (System down/Data loss)
        - High (Major feature broken)
        - Medium (Feature impaired)
        - Low (Minor inconvenience)
    validations:
      required: true

  - type: dropdown
    id: current_status
    attributes:
      label: Current Status
      description: Current state of the bug
      options:
        - New (Not yet investigated)
        - Investigating (Looking into it)
        - Identified (Root cause known)
        - Blocked (Dependencies/Info needed)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment did this occur in?
      placeholder: |
        - Browser: [e.g. Chrome, Safari]
        - Version: [e.g. 22]
        - Operating System: [e.g. Windows, macOS]
        - Environment: [e.g. Production, Staging, Development]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other context, screenshots, or relevant information
      placeholder: "Add any other context about the problem here"
    validations:
      required: false 