name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
        This issue will automatically appear in our organization-wide project board.

  - type: input
    id: project_context
    attributes:
      label: Project Context
      description: What area of the project does this feature relate to?
      placeholder: "e.g., UI/UX, Backend, Testing, Documentation"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve with this feature?
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "A clear and concise description of what you want to happen"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: "A clear and concise description of any alternative solutions or features you've considered"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: "Add any other context, screenshots, or examples about the feature request here"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to the project?
      options:
        - Low (Nice to have)
        - Medium (Important but not urgent)
        - High (Critical for project success)
    validations:
      required: true 