name: Repository Maintenance
on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  stale-management:
    name: Manage Stale Items
    runs-on: ubuntu-latest
    steps:
      - name: Stale issue and PR management
        uses: actions/stale@v8
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs.'
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-message: 'This PR has been automatically marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'

  broken-links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check README and documentation links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '*.md' 'docs/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
